### PR TITLE
refactored so that API_URL is defined in one place in app.js

### LINKED ISSUE #139: Refactor API_URL in JS
Currently, the API_URL is in 3 separate places in the JS.

This should be refactored so it can be in only 1 place.

### PR DESCRIPTION
**Pull request by virgilib**
fixes #139

### CODE REVIEW

**Comment by chrishenry** [comment]
Sweet refactor! 

Quick question; does this change make `API_URL` into a global? Or asked another way, could we do the same thing, but put the definition of `API_URL` in a script tag in the head? Would that still work with Angular?

Reason I ask is that we want to move to a place where that value can be defined without changing code. As in, someone deploying this could change an environment variable, which would be output in the head, and then picked up by the Angular app.

**Comment by virgilib** [comment]
Ah ok I see what you're saying!  As far as I know, putting the environment variable in the script tag in the head works for server-side variables but wouldn't get it into the client-side JS.  Let me think about it some more.

**Comment by virgilib** [comment]
How about something like this?

**Comment by chrishenry** [comment]
Yea, i think that moves us forward a bit. So, if I were to output a script tag onto the head on every page like;

```html
<script>
ENV = {
    API_URL: "/new/api/url"
}
</script>
```
would that value be passed through?

**Comment by virgilib** [comment]
I don't think so since the env.js approach moves API_URL to an environment file like how variables are defined in .env to allow for the variable to be changed without touching the AngularJS app.

I'll have to think a bit more about how to read the variable from a script tag! Thanks for clarifying.

**Comment by chrishenry** [comment]
@virgilib I think this is a big step forward from what we have, so let's get it merged! Thanks!

Keep thinking about how you'd pass vars through script tags, and let me know if you need any help!

**Comment by rdlester** [comment]
Re @virgilib - pretty sure a script tag with inline JS is exactly equivalent to a script tag with the same JS but in a file. Either way, context is shared across tags, so as long as the variable is set globally (or on the window) other stuff should be able to pick it up.

However, because of this equivalence, I'm not sure why you'd prefer one approach over the other. I think (though it's not stated) that the reason Chris is interested in this is for setting up local / test / prod server endpoints that can be automatically set up according to a flag. I think either approach (env file v. raw script tag) would involve adding a step to compilation, I guess the question is which step is easier? I prefer the JS file, just for the sake of keeping all JS stuff in JS files, but I'm not familiar with Rails so I don't know what the typical setup is.

**Comment by rdlester** [comment]
Also - Sorry, but this is definitely not injecting API_URL into the Services as exists now. Putting "console.log(ENV.API_URL + "/query?")" into the HomeService yields "undefined/query?" which results in all service calls to mysteriously no-op (on the Home page at least, neither the "then" nor the "error" are getting called, only "finally").

I'm going to revert this. We should be better about testing stuff.

**Comment by chrishenry** [comment]
Hmm, shouldn't have tests caught that?

**Comment by rdlester** [comment]
I don't think any real tests are set up for the JS code yet? If so, they probably aren't set up for the Services.

**Comment by rdlester** [comment]
There is one test but it's not doing anything:
https://github.com/chrishenry/deltanyc-heatseek/blob/master/angular-rails-app/spec/javascripts/controllerTest_spec.js

**Comment by rdlester** [comment]
See #101

**Comment by rdlester** [comment]
Sorry for the quick / sudden revert, just want to fully verify everything is working prior prior to showing the MVP.

**Comment by virgilib** [comment]
Ah sorry about this!  My development environment must be set up wrong so my code wasn't getting tested....  Will debug and fix.

**Pull request merged**
